---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: azure
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Azure Clusters & Apps
  destinations:
  - namespace: '*'
    name: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - PLACEHOLDER
