---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects-argoapp
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: PLACEHOLDER
    targetRevision: main
    path: projects
  syncPolicy:
    automated:
      prune: true
      selfHeal: true